name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type: Bug", "Status: Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks :heart: for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can the bug be reproduced?
      description: Tell us how we can reproduce the bug.
      placeholder: What did you do?
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our plugin are you using?
      placeholder: 20240328
    validations:
      required: true